import { getFirebaseServices } from './firebase-app.js';
import { getCurrentUserProfile, getUserProfile } from './user-service.js';
import { getProductById } from './product-service.js';

const fromDoc=snapshot=>({id:snapshot.id,...snapshot.data()});
async function activeRequester(){const{auth}=await getFirebaseServices();if(!auth.currentUser)throw Object.assign(new Error('Debes iniciar sesión.'),{code:'auth/unauthenticated'});const profile=await getCurrentUserProfile();if(!profile||profile.status!=='active')throw Object.assign(new Error('Tu cuenta no está activa.'),{code:'auth/user-blocked'});return{uid:auth.currentUser.uid,profile};}

export async function createRequest(data){const{uid,profile}=await activeRequester();const product=await getProductById(data.productId);if(!product||product.status!=='active'||product.moderationStatus!=='approved')throw Object.assign(new Error('El producto ya no está disponible.'),{code:'failed-precondition'});if(product.ownerId===uid)throw Object.assign(new Error('No puedes solicitar tu propio producto.'),{code:'request/own-product'});const owner=await getUserProfile(product.ownerId);if(!owner||owner.status!=='active')throw Object.assign(new Error('El propietario no está disponible.'),{code:'request/owner-inactive'});const{db,dbSdk}=await getFirebaseServices();const pending=await dbSdk.getDocs(dbSdk.query(dbSdk.collection(db,'requests'),dbSdk.where('requesterId','==',uid),dbSdk.where('status','==','pending')));if(pending.docs.some(doc=>doc.data().productId===product.id))throw Object.assign(new Error('Ya tienes una solicitud pendiente para este producto.'),{code:'already-exists'});const type=data.type||({sale:'purchase',loan:'loan',exchange:'exchange'}[product.transactionType]||'purchase');const reference=await dbSdk.addDoc(dbSdk.collection(db,'requests'),{productId:product.id,productTitle:product.title,ownerId:product.ownerId,requesterId:uid,requesterDisplayName:profile.displayName||profile.email,requesterPhotoURL:profile.photoURL||'',type,message:String(data.message||'').trim(),offeredProductId:data.offeredProductId||'',status:'pending',createdAt:dbSdk.serverTimestamp(),updatedAt:dbSdk.serverTimestamp()});return reference.id;}

async function listByParticipant(field,uid,filters={}){const{db,dbSdk}=await getFirebaseServices();const snapshot=await dbSdk.getDocs(dbSdk.query(dbSdk.collection(db,'requests'),dbSdk.where(field,'==',uid),dbSdk.orderBy('createdAt','desc'),dbSdk.limit(filters.limit||100)));return snapshot.docs.map(fromDoc).filter(item=>!filters.status||item.status===filters.status);}
export const listReceivedRequests=(uid,filters={})=>listByParticipant('ownerId',uid,filters);
export const listSentRequests=(uid,filters={})=>listByParticipant('requesterId',uid,filters);

async function ownerTransition(id,status){const{auth,db,dbSdk}=await getFirebaseServices();if(!auth.currentUser)throw Object.assign(new Error('Debes iniciar sesión.'),{code:'auth/unauthenticated'});await dbSdk.runTransaction(db,async transaction=>{const requestRef=dbSdk.doc(db,'requests',id),requestSnap=await transaction.get(requestRef);if(!requestSnap.exists()||requestSnap.data().ownerId!==auth.currentUser.uid)throw Object.assign(new Error('No puedes responder esta solicitud.'),{code:'permission-denied'});if(requestSnap.data().status!=='pending')throw Object.assign(new Error('La solicitud ya fue respondida.'),{code:'failed-precondition'});transaction.update(requestRef,{status,updatedAt:dbSdk.serverTimestamp()});if(status==='accepted')transaction.update(dbSdk.doc(db,'products',requestSnap.data().productId),{status:'reserved',updatedAt:dbSdk.serverTimestamp()});});}
export const acceptRequest=id=>ownerTransition(id,'accepted');
export const rejectRequest=id=>ownerTransition(id,'rejected');

export async function cancelRequest(id){const{auth,db,dbSdk}=await getFirebaseServices();const reference=dbSdk.doc(db,'requests',id),snapshot=await dbSdk.getDoc(reference);if(!snapshot.exists()||snapshot.data().requesterId!==auth.currentUser?.uid||snapshot.data().status!=='pending')throw Object.assign(new Error('No puedes cancelar esta solicitud.'),{code:'permission-denied'});await dbSdk.updateDoc(reference,{status:'cancelled',updatedAt:dbSdk.serverTimestamp()});}

export async function completeRequest(id){const{auth,db,dbSdk}=await getFirebaseServices();if(!auth.currentUser)throw Object.assign(new Error('Debes iniciar sesión.'),{code:'auth/unauthenticated'});await dbSdk.runTransaction(db,async transaction=>{const requestRef=dbSdk.doc(db,'requests',id),requestSnap=await transaction.get(requestRef);if(!requestSnap.exists()||requestSnap.data().ownerId!==auth.currentUser.uid||requestSnap.data().status!=='accepted')throw Object.assign(new Error('No puedes completar esta solicitud.'),{code:'permission-denied'});const request=requestSnap.data(),productRef=dbSdk.doc(db,'products',request.productId),productSnap=await transaction.get(productRef);if(!productSnap.exists())throw Object.assign(new Error('Producto no encontrado.'),{code:'not-found'});const type={purchase:'sale',loan:'loan',exchange:'exchange'}[request.type],productStatus={sale:'sold',loan:'loaned',exchange:'exchanged'}[type],historyRef=dbSdk.doc(dbSdk.collection(db,'transactions'));transaction.update(requestRef,{status:'completed',updatedAt:dbSdk.serverTimestamp()});transaction.update(productRef,{status:productStatus,updatedAt:dbSdk.serverTimestamp()});transaction.set(historyRef,{productId:request.productId,productTitle:request.productTitle,ownerId:request.ownerId,requesterId:request.requesterId,requestId:id,type,status:'completed',createdAt:request.createdAt,completedAt:dbSdk.serverTimestamp()});});}
export async function listRequests(uid,received=true){return received?listReceivedRequests(uid):listSentRequests(uid);}
