import { cartStore,sendPurchaseRequests,validateCart } from '../repositories/cart-repository.js';
import { formatCurrency } from '../utils/formatters.js';
import { createEmptyState } from '../components/empty-state.js';
import { clearElement,createElement } from '../utils/dom.js';
import { updateCartCount } from '../components/header.js';
import { showAlert } from '../components/alert.js';
import { getErrorMessage } from '../utils/errors.js';
const list=document.querySelector('#cartItems');
function render(cart=cartStore.all()){clearElement(list);if(!cart.length)list.append(createEmptyState('Tu carrito está vacío','Agrega productos de venta desde el catálogo.','bi-cart-x'));cart.forEach(item=>{const row=createElement('article',{className:'cart-item'}),image=createElement('img',{attrs:{src:item.imageURLs?.[0]||'../assets/img/placeholders/product.svg',alt:''}}),info=createElement('div');info.append(createElement('h2',{className:'h6',text:item.title}),createElement('strong',{text:formatCurrency(item.price)}));const label=createElement('label',{text:'Cantidad'}),input=createElement('input',{className:'form-control',attrs:{type:'number',min:'1',max:String(item.available||1),value:String(item.quantity),'aria-label':`Cantidad de ${item.title}`}});input.onchange=event=>{cartStore.update(item.id,event.target.value);render();};label.append(input);const remove=createElement('button',{className:'btn btn-outline-danger btn-sm',attrs:{type:'button','aria-label':`Quitar ${item.title}`}});remove.append(createElement('i',{className:'bi bi-trash'}));remove.onclick=()=>{cartStore.remove(item.id);render();};row.append(image,info,label,remove);list.append(row);});const total=cart.reduce((sum,item)=>sum+item.price*item.quantity,0),units=cart.reduce((sum,item)=>sum+item.quantity,0);document.querySelector('#cartUnits').textContent=units;document.querySelector('#cartSubtotal').textContent=formatCurrency(total);document.querySelector('#cartTotal').textContent=formatCurrency(total);updateCartCount();}
try{render(await validateCart());}catch(error){console.error('No se pudo validar el carrito.',error);showAlert(getErrorMessage(error),'warning');render();}
document.querySelector('#clearCart').onclick=()=>{if(confirm('¿Vaciar todo el carrito?')){cartStore.clear();render();}};
document.querySelector('#finishCart').onclick=async event=>{event.currentTarget.disabled=true;try{const result=await sendPurchaseRequests();render();showAlert(`${result.sent} solicitud(es) de compra enviada(s)${result.failed?`; ${result.failed} permanecen en el carrito`:''}.`,result.sent?'success':'warning');}catch(error){showAlert(getErrorMessage(error),'danger');}finally{event.currentTarget.disabled=false;}};
