import { createProduct, getProductById, updateProduct } from '../repositories/product-repository.js';
import { getSession } from '../repositories/session-repository.js';
import { validateForm } from '../utils/validators.js';
import { showAlert } from '../components/alert.js';
import { getErrorMessage } from '../utils/errors.js';

const form=document.querySelector('#productForm'),type=form?.elements.transactionType,price=document.querySelector('#priceGroup'),loan=document.querySelector('#loanGroup'),exchange=document.querySelector('#exchangeGroup'),id=new URLSearchParams(location.search).get('id');
function conditional(){price.hidden=type.value!=='sale';form.elements.price.required=type.value==='sale';loan.hidden=type.value!=='loan';exchange.hidden=type.value!=='exchange';}
type?.addEventListener('change',conditional);conditional();
if(id){try{const[product,session]=await Promise.all([getProductById(id),getSession()]);if(!product||product.ownerId!==session.profile?.uid)throw Object.assign(new Error('No puedes editar esta publicación.'),{code:'permission-denied'});for(const[key,value]of Object.entries(product)){if(form.elements[key]&&!Array.isArray(value))form.elements[key].value=value??'';}conditional();}catch(error){showAlert(getErrorMessage(error),'danger');form.querySelectorAll('input,select,textarea,button').forEach(field=>field.disabled=true);}}
form?.elements.images.addEventListener('change',event=>{const root=document.querySelector('#imagePreview');root.replaceChildren(...[...event.target.files].map(file=>{const img=document.createElement('img');img.src=URL.createObjectURL(file);img.alt=`Vista previa de ${file.name}`;return img;}));});
form?.addEventListener('submit',async event=>{event.preventDefault();if(!validateForm(form))return;const submit=form.querySelector('[type="submit"]'),original=submit.textContent;submit.disabled=true;try{const data=Object.fromEntries(new FormData(form));const payload={title:data.title.trim(),description:data.description.trim(),category:data.category,transactionType:data.transactionType,price:Number(data.price)||0,condition:data.condition,campus:data.campus,quantity:Number(data.quantity)||1,loanConditions:data.loanConditions?.trim()||'',exchangePreferences:data.exchangePreferences?.trim()||''};if(id)await updateProduct(id,payload);else await createProduct(payload,form.elements.images.files,progress=>{submit.textContent=`Subiendo imágenes ${progress}%`;});showAlert(id?'Publicación actualizada.':'Publicación creada y enviada a moderación.','success');setTimeout(()=>{location.href='mis-productos.html';},500);}catch(error){console.error('No se pudo guardar el producto.',error);showAlert(getErrorMessage(error),'danger');}finally{submit.disabled=false;submit.textContent=original;}});
