import { getAdminStatistics,listReports,updateReportStatus } from '../repositories/admin-repository.js';
import { getProductById } from '../repositories/product-repository.js';
import { getUserProfile } from '../repositories/user-repository.js';
import { createElement } from '../utils/dom.js';
import { formatDate } from '../utils/formatters.js';
import { showAlert } from '../components/alert.js';
import { getErrorMessage } from '../utils/errors.js';

const set=(name,value)=>{const element=document.querySelector(`[data-${name}]`);if(element)element.textContent=String(value);},panel=document.querySelector('.surface');
async function load(){panel.replaceChildren(createElement('p',{className:'p-4',text:'Cargando reportes…'}));try{const[stats,reports]=await Promise.all([getAdminStatistics(),listReports({limit:100})]);const enriched=await Promise.all(reports.map(async report=>({...report,product:await getProductById(report.productId),reporter:await getUserProfile(report.reporterId)})));set('pending-reports',stats.pendingReports);set('reviewed-reports',reports.filter(item=>item.status==='reviewed').length);panel.replaceChildren(createElement('h2',{className:'h4',text:'Reportes recientes'}));if(!enriched.length)panel.append(createElement('p',{className:'text-secondary',text:'No hay reportes registrados.'}));enriched.forEach(report=>{const row=createElement('div',{className:'report-item'}),info=document.createElement('div');info.append(createElement('strong',{text:report.reason||'Reporte sin motivo'}),createElement('p',{text:`${report.product?.title||'Producto no disponible'} · Reportado por ${report.reporter?.displayName||report.reporterId} · ${formatDate(report.createdAt)}`}),createElement('small',{text:report.description||''}));const actions=createElement('div',{className:'d-flex gap-1'});for(const[label,status]of[['Revisado','reviewed'],['Descartar','dismissed']]){const button=createElement('button',{className:'btn btn-outline-primary btn-sm',text:label,attrs:{type:'button'}});button.onclick=async()=>{try{await updateReportStatus(report.id,status);showAlert('Reporte actualizado.','success');await load();}catch(error){showAlert(getErrorMessage(error),'danger');}};actions.append(button);}row.append(info,actions);panel.append(row);});}catch(error){showAlert(getErrorMessage(error),'danger');panel.replaceChildren(createElement('p',{className:'p-4 text-danger',text:'No se pudieron cargar los reportes.'}));}}await load();
