import{getSession}from'../repositories/session-repository.js';import{listProductsByOwner,listAllProducts,updateProductStatus,softDeleteProduct}from'../repositories/product-repository.js';import{listReceivedRequests,listSentRequests,acceptRequest,rejectRequest,cancelRequest,completeRequest}from'../repositories/request-repository.js';import{listUsers}from'../repositories/user-repository.js';import{setUserStatus,moderateProduct}from'../repositories/admin-repository.js';import{formatCurrency,formatDate,statusLabel,transactionLabel}from'../utils/formatters.js';import{route}from'../utils/routes.js';import{showAlert}from'../components/alert.js';import{createElement}from'../utils/dom.js';import{getErrorMessage}from'../utils/errors.js';
const body=document.querySelector('[data-table-body]'),page=document.body.dataset.page,search=document.querySelector('[data-table-search]');let data=[];
const cell=(...children)=>{const td=document.createElement('td');children.flat().forEach(child=>td.append(child instanceof Node?child:document.createTextNode(String(child??''))));return td;};
const textStack=(main,sub)=>{const fragment=document.createDocumentFragment();fragment.append(createElement('strong',{text:main||'—'}),createElement('small',{text:sub||''}));return fragment;};
const badge=(label,className='text-bg-light')=>createElement('span',{className:`badge ${className}`,text:label});
const button=(label,className,action)=>{const element=createElement('button',{className:`btn btn-sm ${className}`,text:label,attrs:{type:'button'}});element.onclick=async()=>{element.disabled=true;try{await action();showAlert(`Acción “${label}” completada.`,'success');await load();}catch(error){showAlert(getErrorMessage(error),'danger');}finally{element.disabled=false;}};return element;};
const group=(...items)=>{const element=createElement('div',{className:'d-flex flex-wrap gap-1'});element.append(...items);return element;};
function render(items=data){body.replaceChildren();items.forEach(item=>{const tr=document.createElement('tr');
if(page==='my-products'){const edit=createElement('a',{className:'btn btn-sm btn-outline-primary',text:'Editar',attrs:{href:route(`pages/estudiante/editar-producto.html?id=${encodeURIComponent(item.id)}`)}}),requests=createElement('a',{className:'btn btn-sm btn-outline-secondary',text:'Solicitudes',attrs:{href:'solicitudes-recibidas.html'}}),actions=[edit,requests];if(item.status==='active'){actions.push(button('Desactivar','btn-outline-secondary',()=>softDeleteProduct(item.id)));const terminal={sale:['Vendido','sold'],loan:['Prestado','loaned'],exchange:['Intercambiado','exchanged']}[item.transactionType];if(terminal)actions.push(button(terminal[0],'btn-outline-success',()=>updateProductStatus(item.id,terminal[1])));}tr.append(cell(textStack(item.title,item.category)),cell(transactionLabel(item.transactionType)),cell(item.transactionType==='sale'?formatCurrency(item.price):'—'),cell(badge(statusLabel(item.status),item.status==='active'?'text-bg-success':'text-bg-light')),cell(group(...actions)));}
if(page==='requests-received'||page==='requests-sent'){const actions=[];if(page==='requests-received'&&item.status==='pending')actions.push(button('Aceptar','btn-outline-success',()=>acceptRequest(item.id)),button('Rechazar','btn-outline-danger',()=>rejectRequest(item.id)));if(page==='requests-received'&&item.status==='accepted')actions.push(button('Completar','btn-outline-primary',()=>completeRequest(item.id)));if(page==='requests-sent'&&item.status==='pending')actions.push(button('Cancelar','btn-outline-danger',()=>cancelRequest(item.id)));tr.append(cell(textStack(item.productTitle,item.requesterDisplayName)),cell(transactionLabel(item.type==='purchase'?'sale':item.type)),cell(formatDate(item.createdAt)),cell(badge(statusLabel(item.status))),cell(actions.length?group(...actions):'Sin acciones'));}
if(page==='admin-users'){const view=createElement('a',{className:'btn btn-sm btn-outline-primary',text:'Ver',attrs:{href:`usuario-detalle.html?id=${encodeURIComponent(item.uid)}`}}),toggle=button(item.status==='active'?'Bloquear':'Activar','btn-outline-secondary',()=>setUserStatus(item.uid,item.status==='active'?'blocked':'active'));tr.append(cell(textStack(item.displayName,item.email)),cell(item.career||'—'),cell(item.campus||'—'),cell(item.role),cell(badge(statusLabel(item.status),item.status==='active'?'text-bg-success':'text-bg-danger')),cell(formatDate(item.createdAt)),cell(group(view,toggle)));}
if(page==='admin-products'){const view=createElement('a',{className:'btn btn-sm btn-outline-primary',text:'Ver',attrs:{href:route(`pages/producto.html?id=${encodeURIComponent(item.id)}`)}});tr.append(cell(textStack(item.title,item.ownerDisplayName)),cell(transactionLabel(item.transactionType)),cell(item.category),cell(statusLabel(item.status)),cell(badge(statusLabel(item.moderationStatus))),cell(formatDate(item.createdAt)),cell(group(view,button('Aprobar','btn-outline-success',()=>moderateProduct(item.id,'approved')),button('Ocultar','btn-outline-danger',()=>moderateProduct(item.id,'hidden')),button('Rechazar','btn-outline-secondary',()=>moderateProduct(item.id,'rejected')))));}
body.append(tr);});if(!items.length){const tr=document.createElement('tr');tr.append(createElement('td',{className:'text-center text-secondary py-5',text:'No hay registros para mostrar.',attrs:{colspan:'7'}}));body.append(tr);}}
async function load(){body.replaceChildren();const tr=document.createElement('tr');tr.append(createElement('td',{className:'text-center py-5',text:'Cargando datos…',attrs:{colspan:'7'}}));body.append(tr);try{const{profile}=await getSession();if(page==='my-products')data=await listProductsByOwner(profile.uid,{limit:100});if(page==='requests-received')data=await listReceivedRequests(profile.uid,{limit:100});if(page==='requests-sent')data=await listSentRequests(profile.uid,{limit:100});if(page==='admin-users')data=await listUsers({limit:200});if(page==='admin-products')data=await listAllProducts({limit:200});render();}catch(error){console.error('No se pudo cargar la tabla.',error);showAlert(getErrorMessage(error),'danger');render([]);}}
search?.addEventListener('input',event=>{const term=event.target.value.toLowerCase();render(data.filter(item=>Object.values(item).some(value=>String(value??'').toLowerCase().includes(term))));});
document.querySelector('.table-tools select')?.addEventListener('change',event=>{const value=event.target.value.toLowerCase();if(value.startsWith('todo'))return render();render(data.filter(item=>[item.status,item.role,item.moderationStatus,item.campus].some(field=>String(field||'').toLowerCase()===value)));});
await load();
