import { createElement } from '../utils/dom.js';
import { formatCurrency, transactionLabel } from '../utils/formatters.js';
import { isFavorite, toggleFavorite } from '../repositories/favorite-repository.js';
import { route } from '../utils/routes.js';
import { getErrorMessage } from '../utils/errors.js';

const icon = name => createElement('i',{className:`bi ${name}`,attrs:{'aria-hidden':'true'}});

export function createProductCard(product,{onCart,onFavorite,onError}={}){
  const article=createElement('article',{className:'product-card reveal'});const media=createElement('div',{className:'product-card__media'});const image=createElement('img',{attrs:{src:product.imageURLs?.[0]||route('assets/img/placeholders/product.svg'),alt:product.title||'Producto sin título',loading:'lazy'}});const favorite=createElement('button',{className:'favorite-btn',attrs:{type:'button','aria-label':'Guardar en favoritos'}});
  const paint=active=>favorite.replaceChildren(icon(active?'bi-heart-fill':'bi-heart'));paint(false);isFavorite(product.id).then(paint).catch(()=>{});favorite.addEventListener('click',async()=>{favorite.disabled=true;try{const active=await toggleFavorite(product.id);paint(active);onFavorite?.(active);}catch(error){onError?.(getErrorMessage(error),error);if(error.code==='auth/unauthenticated')location.href=route(`pages/login.html?next=${encodeURIComponent(location.pathname+location.search)}`);}finally{favorite.disabled=false;}});media.append(image,favorite);
  const body=createElement('div',{className:'product-card__body'});const meta=createElement('div',{className:'d-flex justify-content-between gap-2 mb-2'});meta.append(createElement('span',{className:`badge type-${product.transactionType}`,text:transactionLabel(product.transactionType)}),createElement('small',{text:product.condition||''}));const title=createElement('h3',{text:product.title||'Sin título'});const price=createElement('strong',{className:'product-card__price',text:product.transactionType==='sale'?formatCurrency(product.price):transactionLabel(product.transactionType)});const location=createElement('p',{className:'small text-secondary',text:`${product.campus||'Campus no indicado'} · ${product.category||'Sin categoría'}`});const actions=createElement('div',{className:'d-flex gap-2 mt-auto'});const detail=createElement('a',{className:'btn btn-outline-primary btn-sm flex-grow-1',text:'Ver detalle',attrs:{href:route(`pages/producto.html?id=${encodeURIComponent(product.id)}`)}});actions.append(detail);if(product.transactionType==='sale'&&onCart){const add=createElement('button',{className:'btn btn-primary btn-sm',attrs:{type:'button','aria-label':'Agregar al carrito'}});add.append(icon('bi-cart-plus'));add.addEventListener('click',()=>onCart(product));actions.append(add);}body.append(meta,title,price,location,actions);article.append(media,body);return article;
}
